title: "Antura"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Antura on GitHub":
    - "//github.com/vgwb/Antura"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true